// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfdzckmpkkcdzaekogkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmZHpja21wa2tjZHphZWtvZ2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODAzMTQsImV4cCI6MjA2NjY1NjMxNH0.BwdOFFvX4WtscF80BGo2VFdOkAL9mR8ftbIM3R2JeP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);